spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mydb?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  session:
    store-type: none
  port: 8080